language: node_js
node_js:
  - "8.9.3"
install:
  - npm install
script:
  - npm run lint
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages
